//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HyoutaTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HyoutaTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body { background-color: #68504F; color: #EFD1AE; font-size: 16; }
        ///.itemname { color: #FFEBD2; font-size: 20; }
        ///.itemdesc { }
        ///.equip { text-align: right; float: right; }
        ///.special { text-align: right; float: right; }
        ///table, tr, td, th { padding: 0px 4px 0px 0px; border-spacing: 0px; }
        ///td, td &gt; a { vertical-align: top; }
        ///a:link, a:visited, a:hover, a:active { color: #FFEBD2; }
        ///table.element { display: inline-block; }
        ///table.element td { text-align: center; padding: 0px 8px 0px 8px; border-spacing: 0px [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vesperia_website_general_css {
            get {
                return ResourceManager.GetString("vesperia_website_general_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.scenario-content {
        ///    overflow: hidden;
        ///}
        ///div.scenario-previous-next {
        ///}
        ///div.storyBox {
        ///    margin-top: 10px;
        ///}
        ///
        ///.storyBlock {
        ///    display: inline-block;
        ///    vertical-align: top;
        ///    width: 480px;
        ///    padding-right: 20px;
        ///    text-align: center;
        ///}
        ///
        ///.skitBlock {
        ///    display: inline-block;
        ///    vertical-align: top;
        ///    width: 450px;
        ///    text-align: left;
        ///}
        ///
        ///.storyText {
        ///    /* font-family: &quot;Baskerville&quot;,serif; */
        ///    position: relative;
        ///    padding-bottom: 20px;
        ///    color: #2f1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vesperia_website_scenario_css {
            get {
                return ResourceManager.GetString("vesperia_website_scenario_css", resourceCulture);
            }
        }
    }
}
